# ML-Fundamentals - Python Numpy Basics

## Table of Contents
* [Introduction](#Introduction)
* [Requirements](#Requirements) 
  * [Knowledge](#Knowledge) 
  * [Modules](#Python-Modules)
* [Exercises](#Exercises)
* [Summary and Outlook](#Summary-and-Outlook)
* [Literature](#Literature) 
* [Licenses](#Licenses)

## Introduction

In this exercise you will learn numpy operations / features, which you will need throughout nearly all data science tasks, when working with python.

## Requirements
### Knowledge

You should have a basic knowledge of:
- numpy

Suitable sources for acquiring this knowledge are:
- [numpy quickstart](https://docs.scipy.org/doc/numpy-1.15.1/user/quickstart.html)
- [numpy slicing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)

### Python Modules

By [deep.TEACHING](https://www.deep-teaching.org/) convention, all python modules needed to run the notebook are loaded centrally at the beginning. 


In [1]:
# External Modules
import numpy as np

## Exercises

**Task:**

Generate a numpy-1D array of length 10, all elements being 0, except the 5th element which is 1

In [2]:
### Your Solution
a =  np.array( [0,0,0,0,1,0,0,0,0,0] )
print(a)

[0 0 0 0 1 0 0 0 0 0]


**Task:**

Reverse the order of vector `z`: The first element becomes the last, the second becomes the second last etc.

In [3]:
### Your Solution
z = np.arange(50)
z = np.flip(z)
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


**Task:**

Find the indices of all elements that are nonzero.

In [4]:
### Your Solution
z = np.array([1,2,0,0,4,0])
index = np.where(z!=0)
print(index)

(array([0, 1, 4], dtype=int64),)


**Task:**

Generate a 10x10 array with random values and find the smallest and largest value.

In [5]:
### Your Solution
random = np.random.rand(10,10)
minValue = np.amin(random)
maxValue = np.amax(random)
print(random)
print(minValue)
print(maxValue)

[[0.85140747 0.53741814 0.0728169  0.32107722 0.17964191 0.22137819
  0.67713278 0.14047986 0.40459845 0.90143029]
 [0.17597219 0.59975354 0.43661212 0.7259962  0.29346264 0.6655025
  0.01280192 0.90829693 0.78525164 0.19122198]
 [0.15529718 0.35466458 0.28567088 0.73892411 0.07430292 0.60157992
  0.44432214 0.99425156 0.66033508 0.09284525]
 [0.81144002 0.51845668 0.89828584 0.33817774 0.34746656 0.6137511
  0.1600866  0.60580723 0.59071847 0.37769522]
 [0.53091331 0.37382619 0.87353583 0.73834102 0.1364179  0.95957498
  0.10667144 0.042914   0.49308944 0.62791309]
 [0.5559199  0.8591116  0.78946052 0.08105139 0.98320758 0.09047154
  0.34401437 0.03415854 0.32305966 0.92382578]
 [0.38549293 0.9472067  0.64463019 0.40820694 0.93099169 0.25007847
  0.4231713  0.88879046 0.59545754 0.01357982]
 [0.90870743 0.28028742 0.75024592 0.65490476 0.10418263 0.43175533
  0.24505226 0.27624997 0.51276869 0.94749573]
 [0.9038397  0.97084485 0.54261954 0.61823183 0.23183802 0.82585129
  0.7969     0

**Task:**

Generate a vector of length 50 with random values and calculate the mean.

In [6]:
### Your Solution
vector = np.random.rand(50)
mean = np.mean(vector)
print(vector)
print(mean)

[0.37639739 0.60845198 0.51151675 0.54647386 0.99737386 0.49156215
 0.58057313 0.3252552  0.2729964  0.02892256 0.55834774 0.66913035
 0.86907298 0.96674522 0.20634494 0.10197054 0.32090791 0.46162022
 0.66102925 0.02080032 0.10076092 0.41510323 0.78936214 0.97985784
 0.7111065  0.46515631 0.24143432 0.85284387 0.46423406 0.83660865
 0.93871497 0.7575536  0.14493813 0.16926961 0.5843654  0.18927229
 0.51609221 0.24276065 0.5991309  0.56902911 0.77698581 0.8509872
 0.24818931 0.09060386 0.41605389 0.12455301 0.64226941 0.11372489
 0.07384477 0.23122283]
0.4742304490431081


**Task:**

Explain the following results:

##### print(0 * np.nan)
print(np.nan == np.nan) //always wrong because they are two different objects
print(np.inf > np.nan)  //cannot compare a number with an object
print(np.nan - np.nan)  //not a number - not a number = also not a number
print(0.3 == 3 * 0.1)   //https://www.sololearn.com/Discuss/1524665/why-is-0-1-3-not-equal-to-0-3-in-python

**Task:**

Generate an 8x8 matrix and fill it with a chess pattern like:

`
array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])
`

In [7]:
### Your Solution
x = np.zeros((10,10),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


**Task:**

Generate a random 5x5 matrix and normalize (scale) it. That means, the smallest value should become 0.0, the largest 1.0

In [10]:
### Your Solution
r = np.random.randint(10, size=10)
print(r)
scaled = np.interp(r, (r.min(), r.max()), (0, +1))
print(scaled)
#(z-zmin)/(zmax-zmin)

[3 9 4 0 8 5 4 4 2 7]
[0.33333333 1.         0.44444444 0.         0.88888889 0.55555556
 0.44444444 0.44444444 0.22222222 0.77777778]


**Task:**

From each row, subtract the maximum value of that row.

In [11]:
### Your Solution
z = np.arange(12).reshape((3,4))
print(z)
res = z.max(axis=1)
print(res)
result = z-res[:, None]
print(result) #https://howtothink.readthedocs.io/en/latest/PvL_06.html



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 3  7 11]
[[-3 -2 -1  0]
 [-3 -2 -1  0]
 [-3 -2 -1  0]]


**Task:**
    
Divide each column by the sum of that column. Then verify that each column adds up to 1.

In [12]:
### Your Solution
z = np.arange(12).reshape((3,4))
print(z)
colmnSum = z.sum(axis=0)
print(colmnSum)
result = z/colmnSum
print(result) #https://howtothink.readthedocs.io/en/latest/PvL_06.html

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
[[0.         0.06666667 0.11111111 0.14285714]
 [0.33333333 0.33333333 0.33333333 0.33333333]
 [0.66666667 0.6        0.55555556 0.52380952]]


**Task:**

Negate all elements between 3 and 8 in place.

In [13]:
### Your Solution
Z = np.arange(11)
m = (Z > 2) & (Z < 9) #mask
Z[m] *= -1
print(Z)


[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]


**Task:**

Explain the result (output) of the following code:

In [14]:
### Your Solution
print(sum(range(5),-1))
from numpy import *
print(sum(range(5), axis=-1)) # axis -1
del sum #das objekt entfernen

9
10


**Task:**

Generate a random vector of length 100 and sort it.

In [15]:
### Your Solution
r = np.random.randint(1000, size=100)
print(r)
sortedArray = np.sort(r)
print(sortedArray)

[897 149 502 908 919  16 168  24 892 326 272 210 373 649 276  45 565 350
 427  54 565 274 791 257 914 171 190 786 893  53  69 802 487 234 853 417
 695 564 658 517 796 984 537 395 369 920  12 189 275 209 529 164 910 672
 705  35 576 160 397 908 259 894  16 845 822 291 630 381 634 183 477 411
 208  50  99 551 506 494 327  37 356 571 737 181 425 800 465 324 394  23
 782 899 353 484 549 328 358 836 560 434]
[ 12  16  16  23  24  35  37  45  50  53  54  69  99 149 160 164 168 171
 181 183 189 190 208 209 210 234 257 259 272 274 275 276 291 324 326 327
 328 350 353 356 358 369 373 381 394 395 397 411 417 425 427 434 465 477
 484 487 494 502 506 517 529 537 549 551 560 564 565 565 571 576 630 634
 649 658 672 695 705 737 782 786 791 796 800 802 822 836 845 853 892 893
 894 897 899 908 908 910 914 919 920 984]


**Task:**

Check if two arrays are equal:

    1. All elements should be exactly the same
    2. Equality within a tolerance

In [16]:
### Your Solution
A = np.random.random((3,4))
B = A.copy()
B[1,2] = A[1,2] * 1.00000000000001
print (A)
print(B)
np.allclose(A, B)

[[0.03246489 0.1296901  0.96214917 0.75666283]
 [0.31284016 0.24155659 0.79790662 0.21906625]
 [0.9920721  0.74574253 0.52113722 0.49980161]]
[[0.03246489 0.1296901  0.96214917 0.75666283]
 [0.31284016 0.24155659 0.79790662 0.21906625]
 [0.9920721  0.74574253 0.52113722 0.49980161]]


True

**Task:**

Generate (as little code as possible) the following matrix with `np.array` and save it as the variable `arr`.

\begin{bmatrix}
1 & 1 & 1 &1  &1 \\ 
1 & 2 & 1 & 1 & 1\\ 
1 & 1 & 3 & 1 & 1\\ 
1 &1  & 1 & 4 & 1
\end{bmatrix}

And calculate:
- the sum of each line
- the sum of each row

In [17]:
### Your Solution
arr = np.ones((4,5), dtype=int)
arr[1,1]=2
arr[2,2]=3
arr[3,3]=4
print(arr)
# diagonal function

[[1 1 1 1 1]
 [1 2 1 1 1]
 [1 1 3 1 1]
 [1 1 1 4 1]]


**Task:**

Generate a 2x2 matrix from `arr`: It shall consist of the 4 values when taking the values of the 2nd and 4th column of arr and the even rows.

Use different methods:
(see http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)
- integer array indexes
- slices
- boolean arrays


In [18]:
### Your Solution

sliced = arr[[1,3],:][:,[1,3]]

print(sliced)


[[2 1]
 [1 4]]


**Task:**

(see http://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html)

Explain the following operations on `arr`

In [19]:
### Your Solution
print(arr)
print('--------1-------')
print(arr * 5.)
print('--------2-------')
print(np.arange(arr.shape[1]))
print(arr * np.arange(arr.shape[1]))
print('--------3------')
print(np.arange(arr.shape[0]))
print(arr.T * np.arange(arr.shape[0]))
print('--------4-------')
print(arr * np.arange(arr.shape[0]))

[[1 1 1 1 1]
 [1 2 1 1 1]
 [1 1 3 1 1]
 [1 1 1 4 1]]
--------1-------
[[ 5.  5.  5.  5.  5.]
 [ 5. 10.  5.  5.  5.]
 [ 5.  5. 15.  5.  5.]
 [ 5.  5.  5. 20.  5.]]
--------2-------
[0 1 2 3 4]
[[ 0  1  2  3  4]
 [ 0  2  2  3  4]
 [ 0  1  6  3  4]
 [ 0  1  2 12  4]]
--------3------
[0 1 2 3]
[[ 0  1  2  3]
 [ 0  2  2  3]
 [ 0  1  6  3]
 [ 0  1  2 12]
 [ 0  1  2  3]]
--------4-------


ValueError: operands could not be broadcast together with shapes (4,5) (4,) 

**Task:**

Calculate the matrix-vector product (dot product) of `arr` and $v$:

with:

$
v = (1,2,3,4,5)^T
$

In [20]:
### Your Solution
u = np.arange(5)
u = u + 1
dotProduct = np.dot(arr,u.T)
print(dotProduct)

[15 17 21 27]


## Summary and Outlook

In this notebook you've picked up many of the essential numpy operations for maths and data science tasks.

The more you use the library, the more of its functionality you'll discover and its usage will grow more intuitive and familiar.

## Licenses

### Notebook License (CC-BY-SA 4.0)

*The following license applies to the complete notebook, including code cells. It does however not apply to any referenced external media (e.g., images).*

Exercise: Python Numpy Basics <br/>
by Klaus Strohmenger <br/>
is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/).<br/>
Based on a work at https://gitlab.com/deep.TEACHING.


### Code License (MIT)

*The following license only applies to code cells of the notebook.*

Copyright 2019 Klaus Strohmenger

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.