# Machine Learning Fundamentals - Linear Algebra - Exercise: Matrix and Vector Operations

## Table of Contents
* [Introduction](#Introduction)
* [Requirements](#Requirements) 
  * [Knowledge](#Knowledge) 
  * [Modules](#Python-Modules)
  * [Data](#Data)
* [Exercise: Pen and Paper Calculation](#Pen-and-Paper-Calculation)
* [Exercise: Implementation of Basic Operations](#Implmentation-of-Basic-Operations)
  * [Vector Addition](#Vector-Addition)
  * [Vector Subtraction](#Vector-Subtraction)
  * [Scalar Multiplication](#Scalar-Multiplication)
  * [Dot Product](#Dot-Product)
  * [Matrix Multiplication](#Matrix-Multiplication)
  * [Transpose](#Transpose)
* [Summary and Outlook](#Summary-and-Outlook)
* [Literature](#Literature) 
* [Licenses](#Licenses) 

## Introduction
This exercise tests knowledge in basics in linear algebra. Knowledge about matrices, vectors, and their operations are essential in understanding more complex machine learning topics, like neural networks. Safe handling of domain-specific notation and concepts is therefore necessary.  

## Requirements

### Knowledge

- Chapter 2 of [Deep Learning](http://www.deeplearningbook.org/contents/linear_algebra.html) by Ian Goodfellow gives a brief introduction into the field
- [Linear Algebra](http://joshua.smcvt.edu/linearalgebra/#current_version) by Jim Hefferson is a open-source textbook with a lot of good exercises
- [Introduction to Linear Algebra](http://math.mit.edu/~gs/linearalgebra/) by Gilbert Strang ist a good domain specific textbook
- [Coding the Matrix: Linear Algebra through Applications to Computer Science](http://codingthematrix.com/) by Philip Klein is focused on a computer science viewpoint

### Python Modules

In [20]:
# External Modules
import numpy as np

### Data
Given are the following matrices:

\begin{equation}
    A =
    \begin{pmatrix}
    4 & 4 & 5 \\
    2 & 1 & 7 \\
    4 & 8 & 3
    \end{pmatrix}
    ,
    B =
    \begin{pmatrix}
    1 & 6 \\
    3 & 1 \\
    5 & 2
    \end{pmatrix}
    ,
    C =
    \begin{pmatrix}
    1 & 4 & 4 \\
    3 & 1 & 2\\
    6 & 7 & 1
    \end{pmatrix}
\end{equation}


and following vectors:

\begin{equation}
    \vec{x} =
    \begin{pmatrix}
    9 \\
    5 \\
    7
    \end{pmatrix}
    ,
    \vec{y} =
    \begin{pmatrix}
    3 \\
    1 \\
    5
    \end{pmatrix}
\end{equation}

In [21]:
# Matrices
A = ([4,4,5],
     [2,1,7],
     [4,8,3])

B = ([1,6],
     [3,1],
     [5,2])

C = ([1,4,4],
     [3,1,2],
     [6,7,1])

# Vectors
x = (9,5,7)
y = (3,1,5)



## Pen and Paper Calculation
Perform following calculations by hand or write some latex in that notebook.

1.  $\vec{x} \cdot \vec{y}$ (dot or inner product)
2.  $\vec{x} * \vec{y}^T$ (matrix product)
3.  $A * B$ 
4.  $B * A$
5.  $A * C$
6.  $C * A$
7.  $(C^T * A^T)^T$
8.  $A \circ C$ (Hadamard or Schur product)
9.  $ \left  \langle A,C \right \rangle_F $ (Frobenius inner product)

## Implementation of Basic Operations
Implement the following functions using the data structure `List` only. The results should be the same as the corresponding Numpy implementation.

### Vector Addition

In [22]:
def vector_add(a: list, b: list): 
    
    z=list(a)
     
    for i in range(len(a)):
        temp= a[i]+b[i]
        z[i]=temp
        
         
    print(z)
    return z     
    raise NotImplementedError


# Test
np.testing.assert_array_almost_equal(vector_add(x,y), np.add(x,y), verbose=True)

[12, 6, 12]


### Vector Subtraction

In [23]:
def vector_sub(a: list, b: list): 
    
    z=list(a)
     
    for i in range(len(a)):
        temp= a[i]-b[i]
        z[i]=temp
          
    print(z)
    return z  



# Testing
np.testing.assert_array_almost_equal(vector_sub(x,y), np.subtract(x,y), verbose=True)

[6, 4, 2]


### Scalar Multiplication

In [24]:
def scalar_mul(r, A):
    z=np.copy(A)
   
    for i in range( len(A)):
        for j in range( len(A[i])): 
            z[i-1][j-1] *=r
        
    return z 
# Testing
sca = 3
np.testing.assert_array_almost_equal(scalar_mul(sca,A), np.multiply(sca,A), verbose=True)
print(np.multiply(sca,A))

[[12 12 15]
 [ 6  3 21]
 [12 24  9]]


### Dot Product

In [25]:
def vec_dot(a, b):
    z=0
    for i in range(len(a)):
        temp= a[i-1]*b[i-1]
        z+=temp
        
        
         
    print(z)
    return z     
    raise NotImplementedError

# Testing
np.testing.assert_array_almost_equal(vec_dot(x,y), np.dot(x,y), verbose=True)

67


### Matrix Multiplication

In [26]:
def matrix_mult(A, B):
    z=[[0 for x in range(len(B[0]))] for y in range(len(A))] 
    print(z)
    for i in range( len(A)):
        for j in range( len(B[i])) : 
            for k in range( len(B)) : 
                z[i][j] += A[i][k] * B[k][j]
    return z 
# Testing
np.testing.assert_array_almost_equal(matrix_mult(A,B), np.matmul(A,B), verbose=True)

[[0, 0], [0, 0], [0, 0]]


### Transpose

In [27]:
def matrix_transpose(A):
    c=A
    
    for i in range( len(A)):
        for j in range( len(A[i])) : 
             c[j-1][i-1] =A[i-1][j-1]
    return c
# Testing
np.testing.assert_array_almost_equal(matrix_transpose(A), np.transpose(A), verbose=True)

## Summary and Outlook

This exercise covered basic operations on vectors and matrices. If the exercise was too complicated, consider the sources mentioned above for a recap. 

## Literature

<table>
    <tr>
        <td>
            <a name="HEF17"></a>[HEF17]
        </td>
        <td>
            Jim Hefferon, "Linear Algebra",Saint Michael's College, USA, 2017
        </td>
    </tr>
    <tr>
        <td>
            <a name="GOO16"></a>[GOO16]
        </td>
        <td>
            Ian Goodfellow, Yoshua Bengio and Aaron Courville, "Deep Learning", MIT Press, 2016
        </td>
    </tr>
    <tr>
        <td>
            <a name="STR16"></a>[STR16]
        </td>
        <td>
           Gilbert Strang, "Introduction to Linear Algebra", Wellesley-Cambridge Press, 2016
        </td>
    </tr>
    <tr>
        <td>
            <a name="KLE13"></a>[KLE13]
        </td>
        <td>
           Gilbert Strang, "Coding the Matrix", Newtonian Press, 2013
        </td>
    </tr>
     

## Licenses

### Notebook License (CC-BY-SA 4.0)

*The following license applies to the complete notebook, including code cells. It does however not apply to any referenced external media (e.g., images).*

Exercise: Matrix and Vector Operations <br/>
by Benjamin Voigt <br/>
is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-sa/4.0/).<br/>
Based on a work at https://gitlab.com/deep.TEACHING.


### Code License (MIT)

*The following license only applies to code cells of the notebook.*

Copyright 2018 Benjamin Voigt

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.